# Suggested data paths when using GPT-NeoX locally
{
  "train-data-paths": [
    "/lustre/orion/csc605/scratch/tejasexpress/laion_test_12m_webdataset/data/{00000..00004}.tar"  
  ],
  "train-data-weights": [
    1.0,
  ],
  "valid-data-paths": ["/lustre/orion/csc605/scratch/tejasexpress/laion_test_12m_webdataset/data/{00000..00004}.tar"],
  "valid-data-weights": [
    1.0,
  ], 
  "test-data-paths": ["/lustre/orion/csc605/scratch/tejasexpress/laion_test_12m_webdataset/data/{00000..00004}.tar",], 
  "test-data-weights": [
    1.0,
  ],


  #"vocab-file": "./che",

  
  "tokenizer-type": "HFGPT2Tokenizer",

  "save": "./magma_test64",
  # "load": "/gpfs/alpine/csc499/scratch/kshitijkg/neox_converted_magma/mp1_pp1/pythia",
  "load": "./magma_test64",
  #"load_clip": "/gpfs/alpine/csc499/proj-shared/magma/models/clip",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "./tensorboard",
  "log-dir": "./logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "magma_test64",

  "launcher": "slurm",
  "deepspeed_slurm": true,
  # "finetune": true,
  "num_workers": 0,
}
